### ISSUE TITLE
Show a dialog

### ISSUE THREAD

**Issue by scitbiz** [flutter-view/flutter-view#19]
How to show a dialog when clicking a FAB button (pug & HTML)?

**Comment by blueneogeo** [comment]
Hi scitbiz,

If you want to do it all in Pug, you could do it like this (not recommended):

homepage.pug:
```pug
import(package='flutter_view_tools/flutter_view_tools.dart')

home-page(flutter-view)
	builder
		scaffold
			app-bar(as='appBar')
				#title(as='title') Welcome

			center(as='body') Dialog example, pls pet the button

			floating-action-button(
				as='floatingActionButton'
				tooltip='Increment'
				@on-pressed='showDialog(context:context, builder: (context) => HelloDialog())')
				icon(:value='Icons.pets')

hello-dialog(flutter-view)
	builder
		simple-dialog
			.title(as='title') Miauw!
			array(as='children')
				simple-dialog-option(@on-pressed='Navigator.pop(context)') Close
```

You should be able to run the above code with just a simple main that imports and calls HomePage() to render the home.

This homepage.pug example has two flutter-views: the home-page presentation and the hello-dialog presentation. In the home-page view, the scaffold has the FAB, and the @on-pressed event handler calls the Flutter showDialog method. This method uses the hello-dialog view to create the layout for the dialog.

However, the above example is not the recommended way of doing it, as you are polluting your views with code (the showDialog call). Instead, I recommend you pass a view-model into homepage (in this example). This view-model can then have Dart code that performs the showDialog call, and have other logic on handling buttons on your dialog etc.

To see a full example of this in action, please check the [todolist example](https://github.com/flutter-view/examples/tree/master/todolist). In this example, when the user presses the add task FAB, a dialog gets shown that lets the user add the task.

https://github.com/flutter-view/examples/blob/master/todolist/lib/pages/taskspage/taskspage.pug :

```pug
floating-action-button(
	as='floatingActionButton'
	@on-pressed='model.onAddButtonPressed(context)')
	icon(:value='Icons.add')
```
When the button is pressed, the event is handled by the viewmodel, which calls showDialog using the AddTaskDialog flutter-view:

https://github.com/flutter-view/examples/blob/master/todolist/lib/pages/taskspage/taskspage-model.dart :

```dart
onAddButtonPressed(BuildContext context) {
  showDialog(
    context: context,
    builder: (context) => AddTaskDialog(
          controller: this.taskNameController,
          onOk: () {
            // do things here
            Navigator.of(context).pop();
          },
          onCancel: () {
            Navigator.of(context).pop();
          },
        ),
  );
}
```

This way, the layout is handled in Pug, and the actual handling of actions in your layout is handled in Dart, each doing what it does best.

For more information on how to write reactive code in flutter-view, check this page: https://docs.flutter-view.io/guide/writing-reactive-code

**Comment by scitbiz** [comment]
Wow, thanks!
I really like your project. Hope to see more improvement on this (like a better way to solve this problem and more smarter VSCode plugin just like the flutter one)

**Comment by blueneogeo** [comment]
You're most welcome! Glad you are enjoying flutter-view.

It would be nice to add more intellisense, I agree. Not easy though :-)

As for this problem, using the MVVM and delegating to viewmodels/controllers is the intended way you solve this problem in flutter-view. It lets you have clear separation of concerns. I could add special features to make dialogs etc possible in pug, but that would limit you as well, and and make flutter-view more complex.
