### ISSUE TITLE
Apply a style to a TextField's style property 

### ISSUE THREAD

**Issue by spartakb** [flutter-view/flutter-view#21]
Thank you for this great project!   I'm hoping I can get some help with an issue that I'm having.

I'm having a hard time trying to figure out how to get the following output generated from flutter-view:

```
TextField(
      obscureText: false,
      style: TextStyle(fontFamily: 'Montserrat', fontSize: 20.0),
      onChanged: (String value) {
            bloc.updateEmail(value);
      }
    );
```

I have tried the following two approached, and neither results in the desired output above.

## Approach #1

Contents of `.pug` file
```
....
Text-Field.textFieldStyle(
	obscure-Text="false"
	:on-changed='(value){ bloc.updateEmail(value); }'
	)
.....
```

Contents of `.sass` file
```
....
.textFieldStyle
	font-family: Montserrat
	font-size: 20.0
....
```

Contents of `.dart` output file 
__notice how the style is not in a style property, but rather embedded in the `TextField` tag directly__
```
TextField( // project://lib/src/screens/side_menu/test_layout.pug#23,10
  obscureText: false,
  onChanged: (value){ bloc.updateEmail(value); },
  fontFamily: 'Montserrat',
  fontSize: 20.0,
)
```

## Approach #2
Contents of `.pug` file
```
....
Text-Field(
	obscure-Text="false"
	:on-changed='(value){ bloc.updateEmail(value); }'
	)
	Style.textFieldStyle(as="style")
....
```
Same `.sass` file as above.

Contents of `.dart` output file 
__notice how the style property is completely missing__
```
TextField( // project://lib/src/screens/side_menu/test_layout.pug#23,10
  obscureText: false,
  onChanged: (value){ bloc.updateEmail(value); },
)
```

_Note_: If I change the name of the tag to anything else other than `Style`, this outputs the desired effect, it just doesn't work when the tag name is `Style`

**Comment by blueneogeo** [comment]
Hi, 

Glad to help, looking at your code you are very cloe.

For approach 2, this would be the working code:

```pug
text-field(
    :obscure-text='false'
    :on-changed='(value) { bloc.updateEmail(value); }')
    text-style(as='style' font-family='Montserrat', font-size=20)
```

Note the use of text-style instead of style.

For approach 1, the pug code is:

```pug
text-field(
    :obscure-text='false'
    :on-changed='(value) { bloc.updateEmail(value); }')
    text-style.textFieldStyle(as='style')
```

Since you are not styling text, but a separate style, you do need to create that style and assign it. Then by adding the class to the text-style, you can still use sass to style it:

```sass
.textFieldStyle
	font-family: Montserrat
	font-size: 30
```

This will both yield the following code:

```dart
TextField( // project://lib/pages/taskspage/taskspage.pug#9,4
  obscureText: false,
  onChanged: (value) { bloc.updateEmail(value); },
  style: TextStyle( // project://lib/pages/taskspage/taskspage.pug#12,5
    fontFamily: 'Montserrat',
    fontSize: 20,
  ),
),
```

Please let me know if you have any other issues, and enjoy flutter-view :-)

**Comment by spartakb** [comment]
Works perfectly!  Thank you!
