### ISSUE TITLE
quotation marks missing for strings

### ISSUE THREAD

**Issue by soraphis** [flutter-view/flutter-view#24]
screenshot from vscode, above the generated dart code, below is the pug code

![image](https://user-images.githubusercontent.com/3066582/81105844-e312cf00-8f14-11ea-9704-efc95a1ed393.png)

**Comment by blueneogeo** [comment]
Hi @soraphis , that is because you used the : in front of the value attribute. The : indicates you want to pass an expression. To pass a literal value like a string, simply leave out the :. So like this:

```pug
column
  text(value='2nd col')
```

**Comment by soraphis** [comment]
hey, thanks for the fast response!

you might want to check the documentation in this case: https://docs.flutter-view.io/guide/adding-content

(second code example) where the colon is used and it shows the generated code using quotation marks. Problem for me is solved, but you might want to let the issue open until the documentation is changes?

**Comment by blueneogeo** [comment]
Hi, thanks for letting me know, I updated the documentation.

Also as a tip, the text gets automatically generated for you when you pass pug text. So you can also simply do this:

```pug
column 2nd col
```
