### ISSUE TITLE
letter-spacing not supported as a shortcut?

### ISSUE THREAD

**Issue by mlp1802** [flutter-view/flutter-view#26]
I see line-height is, but trying to use letter-spacing fails, even though letter spacing itself is supported by Flutter.

**Comment by blueneogeo** [comment]
Hi, well spotted.

I have added support for this property:

https://docs.flutter-view.io/reference/css-properties#box-shadow-12

I published flutter-view 1.0.2 to NPM:
https://www.npmjs.com/package/flutter-view

After you update flutter-view you should be able to use letter-spacing now.

**Comment by mlp1802** [comment]
Thanks a million!
