### ISSUE TITLE
Cover image example result in wrong Dart code

### ISSUE THREAD

**Issue by mlp1802** [flutter-view/flutter-view#28]
Unless I'm totally missing something then 
`.cover-image(background-image="asset('assets/header.png')" fit="cover")`
Will result in this dart code which doesn't compile
```
Container( // project://lib/screens/header/Header.pug#50,5
    decoration: BoxDecoration( 
      image: DecorationImage( 
        image: ExactAssetImage(
          'assets/header.png',
        ),
      ),
    ),
    width: 200,
    height: 300,
    fit: BoxFit.cover,
  );



```The Fit property is attached to the container instead of to the DecorationImage

**Comment by blueneogeo** [comment]
I just validated this, seems a bug, perhaps introduced in the last update. Will have a look.

**Comment by blueneogeo** [comment]
I found the issue. It is not actually a bug, but may be unclear.

When you want to apply a background cover fit, please use the [background-size](https://docs.flutter-view.io/reference/css-properties#box-shadow-4) CSS property. That was made to work just like CSS, and applies it to the background-image you set with CSS. 

The fit property is there as a shortcut for a [fitted-box](https://api.flutter.dev/flutter/widgets/FittedBox-class.html), and classes that extend that behavior, so you can just use (in pug or with styling): 

```pug
fitted-box(fit="cover") some content here
```

So this should work:

```pug
.cover-image(background-image="asset('assets/header.png')" background-size="cover")
```

I will update the documentation to make these cases clearer.

**Comment by blueneogeo** [comment]
I have updated the documentation of fitted-box to make it clearer to use background-size if you want to set the size of a background-image.
