### ISSUE TITLE
Supporting import sass in pug?

### ISSUE THREAD

**Issue by Shu-Ji** [flutter-view/flutter-view#41]
At this time, we must make pug and sass file the same name.
Such as:
```
home.pug
home.sass
->
home.dart
```

But I want to share sass file between diffient pug files:

```
base.sass
home.pug
about.pug
->
home.dart
about.dart
```

In home.pug:
```pug
import('./base.sass')
.name Home
```

In about.pug:
```pug
import('./base.sass')
.name About
```

In base.sass:
```sass
.name
    color: red
```

**Comment by blueneogeo** [comment]
Hi @Shu-Ji , what you can do is import your base.sass file from other sass files.

In your example, you can do `@import 'base.sass'` inside home.sass. The relative paths are from the root of your project. 

For example, if you have the following file structure with a home and welcome screen:

```
lib
  screens
    home
      home.pug
      home.sass
      home.dart
    welcome
      welcome.pug
      welcome.sass
      welcome.dart
    base.sass
  main.dart
pubspec.yaml
```

Then you can import base.sass from both home.sass and welcome.sass with the following command: `@import 'screens\base.sass'`

This is actually a very powerful feature, and imports work for both pug and sass files, letting you create nice common layout utilities (such as macros in pug).

**Comment by Shu-Ji** [comment]
> 

I forgot this awesome feature! Many thanks!
